/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.carlosaltan.vista;

/**
 *JInternalFrame donde se hace la vista grafica de Cliente
 * @author Carlos Altán
 * @version 1.0
 */
public class VistaClienteG extends javax.swing.JInternalFrame {

    
    private static InsertarCli instanciaAgregarCliente = null;
    private static VerCitaMayor instanciaVerCitaMayor = null; 
   private static MostrarDoc instanciaVerDoctor = null; 
  private static VerClienteMas instanciaVerCliMas = null; 
  
    /**
     * Creates new form VistaClienteG
     */
    public VistaClienteG() {
        initComponents();
    }
    /**
     * Metodo con la instancia de agregar cliente  
     * @return instancia agregar cliente 
     * */
    private synchronized InsertarCli getInstanciAgregarCliente(){
        if (instanciaAgregarCliente == null){
            instanciaAgregarCliente = new InsertarCli();
             instanciaAgregarCliente.setVisible(true);
            jDesktopPane1.add(instanciaAgregarCliente);
            
        }else if (instanciaAgregarCliente.isVisible() == false){
            instanciaAgregarCliente.setVisible(true);
           // jDesktopPane1.add(instanciaAgregarCliente); 
        }
        instanciaAgregarCliente.show();
        return instanciaAgregarCliente; 
    }
    /**
     * Metodo con la instancia de ver cliente 
     * @return instancia de ver cliente
     */
   private synchronized VerCitaMayor getInstancaiVerCiente(){
        if (instanciaVerCitaMayor == null){
            instanciaVerCitaMayor = new VerCitaMayor(); 
             instanciaVerCitaMayor.setVisible(true);
            jDesktopPane1.add(instanciaVerCitaMayor); 
        }else if (instanciaVerCitaMayor.isVisible() == false){
            instanciaVerCitaMayor.setVisible(true);
         
        }
        instanciaVerCitaMayor.show();
        return instanciaVerCitaMayor; 
   }
   /**
    * Metodo con la instancia de verDoctor
    * @return instancia de ver Doctor
    */
   private synchronized MostrarDoc getInstanciaVerDoctor(){
        if (instanciaVerDoctor == null){
            instanciaVerDoctor = new MostrarDoc();
            instanciaVerDoctor.setVisible(true);
            jDesktopPane1.add(instanciaVerDoctor); 
        }else if (instanciaVerDoctor.isVisible() == false){
            instanciaVerDoctor.setVisible(true);
          // jDesktopPane1.add(instanciaVerDoctor); 
        }
        instanciaVerDoctor.show();
        return instanciaVerDoctor; 
    }
     private synchronized VerClienteMas getInstanciaVerMas(){
        if (instanciaVerCliMas == null){
            instanciaVerCliMas = new VerClienteMas();
             instanciaVerCliMas.setVisible(true);
            jDesktopPane1.add(instanciaVerCliMas);
            
        }else if (instanciaVerCliMas.isVisible() == false){
            instanciaVerCliMas.setVisible(true);
          
        }
        instanciaVerCliMas.show();
        return instanciaVerCliMas; 
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDoc = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);

        jDesktopPane1.setBackground(new java.awt.Color(204, 153, 255));
        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1369, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );

        menuDoc.setText("Acceso Doctor");

        jMenuItem4.setText("Ver Doctores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuDoc.add(jMenuItem4);

        jMenuBar1.add(menuDoc);

        jMenu1.setText("Cliente");

        jMenuItem1.setText("Agregar Cita");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ver_Cita");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ver Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       getInstanciaVerDoctor(); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        getInstanciAgregarCliente();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       getInstancaiVerCiente();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        getInstanciaVerMas(); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuDoc;
    // End of variables declaration//GEN-END:variables
}
