/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.carlosaltan.vista;


/**
 *JInterFrame donde se hace la vista grafica de Doctor
 * @author Carlos Altán
 * @version 1.0
 */
public class VistaDoctorG extends javax.swing.JInternalFrame {
    //DOCTOR
      private static InsertarDoc instanciaAgregarDoctor = null; 
    private static MostrarDoc instanciaVerDoctor = null; 
   private static VerCitaMayor instanciaVerCitaMayor = null; 
    private static VerCitasN instanciaVerCitaN = null; 
    private static VerMascota instanciaVerMascota = null; 
    private static VerClienteMas instanciaVerCliMas = null;
    /**
     * Creates new form VistaDoctor
     */
    public VistaDoctorG() {
        initComponents();
        
    }
    /**
     * Metodo con la instancia de agregar  doctor 
     * @return instancia agregar doctor 
     */
    private synchronized InsertarDoc getInstanciaAgregarDoctor(){
        if (instanciaAgregarDoctor == null){
            instanciaAgregarDoctor = new InsertarDoc();
            instanciaAgregarDoctor.setVisible(true);
            jDesktopPane1.add(instanciaAgregarDoctor); 
        }else if (instanciaAgregarDoctor.isVisible() == false){
            instanciaAgregarDoctor.setVisible(true);
           //jDesktopPane1.add(instanciaAgregarDoctor); 
        }
        instanciaAgregarDoctor.show();
        return instanciaAgregarDoctor; 
    }
    /**
     * Metodo con la instancia de ver doctor 
     * @return instancia de ver doctor 
     */
    private synchronized MostrarDoc getInstanciaVerDoctor(){
        if (instanciaVerDoctor == null){
            instanciaVerDoctor = new MostrarDoc();
            instanciaVerDoctor.setVisible(true);
            jDesktopPane1.add(instanciaVerDoctor); 
        }else if (instanciaVerDoctor.isVisible() == false){
            instanciaVerDoctor.setVisible(true);
         
        }
        instanciaVerDoctor.show();
        return instanciaVerDoctor; 
    }
    /**
     * metodo con la instancia de verCita con costo mayor a 120
     * @return instancia de verCiente
     */
    private synchronized VerCitaMayor getInstancaiVerCiente(){
        if (instanciaVerCitaMayor == null){
            instanciaVerCitaMayor = new VerCitaMayor(); 
             instanciaVerCitaMayor.setVisible(true);
            jDesktopPane1.add(instanciaVerCitaMayor); 
        }else if (instanciaVerCitaMayor.isVisible() == false){
            instanciaVerCitaMayor.setVisible(true);
         
        }
        instanciaVerCitaMayor.show();
        return instanciaVerCitaMayor; 
   }
       private synchronized VerCitasN getInstanciaVerCitaN(){
        if (instanciaVerCitaN == null){
            instanciaVerCitaN = new VerCitasN(); 
             instanciaVerCitaN.setVisible(true);
            jDesktopPane1.add(instanciaVerCitaN); 
        }else if (instanciaVerCitaN.isVisible() == false){
            instanciaVerCitaN.setVisible(true);
         
        }
        instanciaVerCitaN.show();
        return instanciaVerCitaN; 
   }
       private synchronized VerMascota getInstanciaVerMascota(){
        if (instanciaVerMascota == null){
            instanciaVerMascota = new VerMascota();
            instanciaVerMascota.setVisible(true);
            jDesktopPane1.add(instanciaVerMascota); 
        }else if (instanciaVerMascota.isVisible() == false){
            instanciaVerMascota.setVisible(true);
           
        }
        instanciaVerMascota.show();
         return instanciaVerMascota; 
       }
       private synchronized VerClienteMas getInstanciaVerMas(){
        if (instanciaVerCliMas == null){
            instanciaVerCliMas = new VerClienteMas();
             instanciaVerCliMas.setVisible(true);
            jDesktopPane1.add(instanciaVerCliMas);
            
        }else if (instanciaVerCliMas.isVisible() == false){
            instanciaVerCliMas.setVisible(true);
          
        }
        instanciaVerCliMas.show();
        return instanciaVerCliMas; 
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setClosable(true);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Ver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/carlosaltan/recursos/docc.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(672, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        menuCliente.setText("Acceso Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        jMenuItem1.setText("VerCitas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem1);

        jMenuItem2.setText("Ver Citas con costa mayor a 120");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem2);

        jMenuItem3.setText("Ver Mascota");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem3);

        jMenuItem4.setText("Ver Clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem4);

        jMenuBar1.add(menuCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * JItem con el getInstancia de ver cliente 
     * @param evt 
     */
   /**
     * JItem con el getInstancia de buscar cliente 
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                
            getInstanciaVerDoctor(); 
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getInstanciaAgregarDoctor(); 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      getInstancaiVerCiente(); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        getInstanciaVerCitaN(); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
         
    }//GEN-LAST:event_menuClienteActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        getInstanciaVerMas(); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       getInstanciaVerMascota();
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCliente;
    // End of variables declaration//GEN-END:variables
}
